[plugins]
android = "com.android.library:7.4.2"
kotlin = "org.jetbrains.kotlin.android:1.8.10"
versions = "com.github.ben-manes.versions:0.46.0"

[libraries]
androidx-core = "androidx.core:core:1.9.0"
androidx-core-ktx = "androidx.core:core-ktx:1.9.0"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-fragment = "androidx.fragment:fragment:1.5.6"
androidx-lifecycle-savedstate = "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0"
androidx-room-runtime = "androidx.room:room-runtime:2.5.1"
androidx-test-core = "androidx.test:core:1.5.0"
gson = "com.google.code.gson:gson:2.10.1"
kotlin-reflect.module = "org.jetbrains.kotlin:kotlin-reflect"
kotlin-stdlib.module = "org.jetbrains.kotlin:kotlin-stdlib"
kotlin-test.module = "org.jetbrains.kotlin:kotlin-test-junit"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
kotlinx-serialization-protobuf = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.5.0"
mockk = 'io.mockk:mockk:1.13.4'
moshi = "com.squareup.moshi:moshi:1.14.0"
moshi-kotlin = "com.squareup.moshi:moshi-kotlin:1.14.0"
robolectric = "org.robolectric:robolectric:4.9.2"
threeten-threetenabp = "com.jakewharton.threetenabp:threetenabp:1.4.4"
threeten-threetenbp = "org.threeten:threetenbp:1.6.7"
