[versions]
kotlin = "2.3.0"

[plugins]
android = "com.android.library:8.13.2"
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
conventions = "xyz.tynn.convention.project:0.0.5"

[libraries]
androidx-annotation = "androidx.annotation:annotation:1.9.1"
androidx-core = "androidx.core:core:1.17.0"
androidx-core-ktx = "androidx.core:core-ktx:1.17.0"
androidx-datastore = "androidx.datastore:datastore:1.2.0"
androidx-fragment = "androidx.fragment:fragment:1.8.9"
androidx-lifecycle-savedstate = "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.9.4"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
androidx-room-runtime = "androidx.room:room-runtime:2.8.4"
androidx-test-core = "androidx.test:core:1.7.0"
androidx-test-runner = "androidx.test:runner:1.7.0"
gson = "com.google.code.gson:gson:2.13.2"
kotlin-reflect.module = "org.jetbrains.kotlin:kotlin-reflect"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.2"
kotlinx-serialization-protobuf = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.10.2"
junit = 'junit:junit:4.13.2'
mockk = 'io.mockk:mockk:1.14.6'
moshi = "com.squareup.moshi:moshi:1.15.2"
moshi-kotlin = "com.squareup.moshi:moshi-kotlin:1.15.2"
robolectric = "org.robolectric:robolectric:4.16"
threeten-abp = "com.jakewharton.threetenabp:threetenabp:1.4.9"
threeten-bp = "org.threeten:threetenbp:1.7.2"

[bundles]
android-test = ["androidx-test-runner", "junit"]
