[versions]
kotlin = "1.8.22"

[plugins]
android = "com.android.library:8.0.2"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
conventions = "xyz.tynn.convention.project:0.0.2"
versions = "com.github.ben-manes.versions:0.47.0"

[libraries]
androidx-core = "androidx.core:core:1.10.1"
androidx-core-ktx = "androidx.core:core-ktx:1.10.1"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-fragment = "androidx.fragment:fragment:1.5.7"
androidx-lifecycle-savedstate = "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0"
androidx-room-runtime = "androidx.room:room-runtime:2.5.2"
androidx-test-core = "androidx.test:core:1.5.0"
gson = "com.google.code.gson:gson:2.10.1"
kotlin-reflect.module = "org.jetbrains.kotlin:kotlin-reflect"
kotlin-stdlib.module = "org.jetbrains.kotlin:kotlin-stdlib"
kotlin-test.module = "org.jetbrains.kotlin:kotlin-test"
kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.1"
kotlinx-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1"
kotlinx-serialization-protobuf = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.5.1"
mockk = 'io.mockk:mockk:1.13.5'
moshi = "com.squareup.moshi:moshi:1.15.0"
moshi-kotlin = "com.squareup.moshi:moshi-kotlin:1.15.0"
robolectric = "org.robolectric:robolectric:4.10.3"
threeten-abp = "com.jakewharton.threetenabp:threetenabp:1.4.6"
threeten-bp = "org.threeten:threetenbp:1.6.8"
