name: Build
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - int

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: build
